version: "3"

services: 
    bot:
        image: greader-bot
        build: ./bot 
        env_file: ./.env.docker
        environment: 
            CRAWLER_HOST: crawler
            NODE_ENV: development
            PGHOST: postgres
            PGPORT: 5432
            PGDATABASE: greader
            PGUSER: docker
            PGPASSWORD: docker
        ports:
            - 9229:9229
        restart: always
        depends_on:
            - crawler
            - postgres
    
    crawler:
        image: greader-crawler
        build: ./crawler 
        env_file: ./.env.docker
        environment: 
            PGHOST: postgres
            PGPORT: 5432
            PGDATABASE: greader
            PGUSER: docker
            PGPASSWORD: docker
        expose:
            - "9090" 
        restart: always
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: greader
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        expose:
            - "5432"

    api:
        image: greader-api
        build: ./api 
        env_file: ./.env.docker
        environment: 
            NODE_ENV: development
            PGHOST: postgres
            PGPORT: 5432
            PGDATABASE: greader
            PGUSER: docker
            PGPASSWORD: docker
        ports:
            - 14000:14000
            - 19229:9229

        restart: always
        depends_on:
            - postgres

