version: "3"

services: 
    bot:
        image: greader-bot
        build: ./bot 
        env_file: ./.env.docker
        environment: 
            CRAWLER_HOST: crawler
        extra_hosts: 
            - host:172.17.0.1
    
    crawler:
        image: greader-crawler
        build: ./crawler 
        env_file: ./.env.docker
        extra_hosts: 
            - host:172.17.0.1
        hostname: crawler 
        ports: 
            - 9090:9090

# expose crawler port to bot instead of to everyone
# expose: [ "9090" ]